// <auto-generated />
namespace CodeFirstLearn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ver01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ver01));
        
        string IMigrationMetadata.Id
        {
            get { return "202412180555266_ver-01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
